"""Task data model for the Todo application.

This module defines the Task dataclass representing a single todo item
with a unique ID, title, and completion status.
"""

from dataclasses import dataclass


@dataclass
class Task:
    """Represents a single todo task.

    A Task is a simple data structure with an ID for identification,
    a title describing what needs to be done, and a completion status
    indicating whether the task has been finished.

    The Task model enforces data integrity through validation in __post_init__,
    ensuring IDs are positive integers and titles are non-empty strings.

    Attributes:
        id: Unique positive integer identifier for the task. Must be > 0.
            IDs are typically auto-generated by TaskManager starting at 1.
        title: Description of the task to be completed. Cannot be empty or
            whitespace-only. Will be trimmed of leading/trailing whitespace
            by TaskManager before Task creation.
        completed: Boolean indicating whether the task is done. Defaults to
            False for new tasks. Set to True when task is marked complete.

    Raises:
        ValueError: If validation fails during initialization (see __post_init__).

    Example:
        >>> task = Task(id=1, title="Buy groceries")
        >>> task.completed
        False
        >>> task.completed = True
        >>> task.title = "Buy groceries and cook dinner"

    Note:
        While id is immutable by convention (should not be changed after
        creation), title and completed are mutable to support update and
        mark-complete operations.
    """

    id: int  # Unique identifier, must be positive (> 0)
    title: str  # Task description, cannot be empty after stripping whitespace
    completed: bool = False  # Completion status, defaults to False

    def __post_init__(self) -> None:
        """Validate task attributes after initialization.

        Ensures data integrity by validating that the ID is a positive integer
        and the title is not empty after removing whitespace.

        Raises:
            ValueError: If id is not a positive integer (id <= 0).
            ValueError: If title is empty or contains only whitespace.
        """
        if self.id <= 0:
            raise ValueError("Task ID must be a positive integer")

        if not self.title.strip():
            raise ValueError("Task title cannot be empty")
